export const routes = {
  en: {
    homepage: '/en/homepage',
    about: '/en/about-author',
    books: '/en/books',
    authors: '/en/authors',
    historyArchives: '/en/history-archives',
    blog: '/en/blog',
    links: 'en/links',
    privacyPolicy: '/en/privacy-policy',
    contact: '/en/contact',
    compromisQualitat: '/en/commitment-responsibility',
  },

  es: {
    homepage: '/es/homepage',
    about: '/es/about-author',
    books: '/es/books',
    authors: '/es/authors',
    historyArchives: '/es/history-archives',
    blog: '/es/blog',
    links: 'es/links',
    privacyPolicy: '/es/privacy-policy',
    contact: '/es/contact',
    compromisQualitat: '/es/commitment-responsibility',
  },

  ca: {
    homepage: '/ca/homepage',
    about: '/ca/about-author',
    books: '/ca/books',
    authors: '/ca/authors',
    historyArchives: '/ca/history-archives',
    blog: '/ca/blog',
    links: 'ca/links',
    privacyPolicy: '/ca/privacy-policy',
    contact: '/ca/contact',
    compromisQualitat: '/ca/commitment-responsibility',
  },

  fr: {
    homepage: '/fr/homepage',
    about: '/fr/about-author',
    books: '/fr/books',
    authors: '/fr/authors',
    historyArchives: '/fr/history-archives',
    blog: '/fr/blog',
    links: 'fr/links',
    privacyPolicy: '/fr/privacy-policy',
    contact: '/fr/contact',
    compromisQualitat: '/fr/commitment-responsibility',
  },

  it: {
    homepage: '/it/homepage',
    about: '/it/about-author',
    books: '/it/books',
    authors: '/it/authors',
    historyArchives: '/it/history-archives',
    blog: '/it/blog',
    links: 'it/links',
    privacyPolicy: '/it/privacy-policy',
    contact: '/it/contact',
    compromisQualitat: '/it/commitment-responsibility',
  },
}
